server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://game.cangehzymkvs.ap-northeast-2.rds.amazonaws.com:3306/game
    username: root
    password: zd72eVugJOAAGiNHLT2q
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb+srv://rnrmf0721:v7JdddChi1jtnAjR@cluster0.pjpvyou.mongodb.net/nerdInDeveloper
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always