server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://game.cangehzymkvs.ap-northeast-2.rds.amazonaws.com:3306/game
    username: root
    password: zd72eVugJOAAGiNHLT2q
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb+srv://rnrmf0721:v7JdddChi1jtnAjR@cluster0.pjpvyou.mongodb.net/nerdInDeveloper
    redis:
      host: localhost
      port: 6379
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: always
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 80d80a8cdee20163339bb014f820b02c
            redirect-uri: http://localhost/auth/kakao/callback
            authorization-grant-type: authorization_code
        provider:
          kakao:
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher